(function(){var f=true,g=false,i=window.h={},k=navigator.userAgent.toLowerCase();k.match(/.+(?:rv|it|ra|ie)[\/: ]([\d.]+)/);var l=/webkit/.test(k),m=/opera/.test(k),n=/msie/.test(k)&&!/opera/.test(k),o=g,p=g,q=[];function r(){if(!p&&(p=f,q)){for(var a=0;a<q.length;a++)q[a].call(window,[]);q=[]}}function s(){var a=r,b=window.onload;window.onload=typeof window.onload!="function"?a:function(){b&&b();a()}}
function t(){if(!o){o=f;document.addEventListener&&!m&&document.addEventListener("DOMContentLoaded",r,g);n&&window==top&&function(){if(!p){try{document.documentElement.doScroll("left")}catch(a){setTimeout(arguments.callee,0);return}r()}}();m&&document.addEventListener("DOMContentLoaded",function(){if(!p){for(var a=0;a<document.styleSheets.length;a++)if(document.styleSheets[a].disabled){setTimeout(arguments.callee,0);return}r()}},g);if(l){var a;(function(){if(!p)if(document.readyState!="loaded"&&document.readyState!=
"complete")setTimeout(arguments.callee,0);else{if(a===void 0){for(var b=document.getElementsByTagName("link"),c=0;c<b.length;c++)b[c].getAttribute("rel")=="stylesheet"&&a++;a+=document.getElementsByTagName("style").length}document.styleSheets.length!=a?setTimeout(arguments.callee,0):r()}})()}s()}}i.ready=function(a){t();p?a.call(window,[]):q.push(function(){return a.call(window,[])})};t();var u=document,v,w="wumii-hook",x="wurl",y="wtitle",k=navigator.userAgent.toLowerCase(),z=g;
if((!/msie/.test(k)||/opera/.test(k))&&!A()&&(typeof wumiiEnableCustomPos=="undefined"||!wumiiEnableCustomPos||document.getElementById("wumiiDisplayDiv")))try{B(),z=f}catch(C){}i.ready(function(){z||(z=f,B())});function A(){if(/\.jimdo\.com$/.test(location.hostname))return f;for(var a=document.getElementsByTagName("link"),b=0;b<a.length;b++){var c=a[b].href;if(c.indexOf("http://u.jimdo.com/")!=-1||c.indexOf("http://s.jimdo.com/")!=-1)return f}return g}
function B(){function a(){v=D(b);if(v.length==1){var a=v[0];if(a.g())a.b.style.display="none";E(a.c(),a.d(),a.a)}else F(),G()}var b=H();if(b.length==0){var c=document.createElement("div");c.className=w;b.push(c);if(A()){if(!/\d{4}\/\d{2}\/\d{2}/.test(document.location.href))return;for(var d=document.getElementById("content_area").getElementsByTagName("div"),e=0;e<d.length;e++)if(d[e].id.indexOf("cc-matrix")!=-1){d[e].appendChild(c);break}}else{var j=u.getElementById("wumiiRelatedItems");if(typeof wumiiParams!=
"undefined"&&wumiiParams.indexOf("pf=CNBLOGS")!=-1)(function(){var b=u.getElementById("MySignature");if(b.length==0||b.innerHTML=="")setTimeout(arguments.callee,25);else{for(var b=b.children,d=0,e=b.length;d<e;d++)if(b[d].id=="wumiiRelatedItems"){j=b[d];break}j&&(j.parentNode.insertBefore(c,j),a())}})();else{if(!j)return;if((d=j.getAttribute("src"))&&d.indexOf("pf=Z-Blog")!=-1||typeof wumiiParams!="undefined"&&wumiiParams.indexOf("pf=Z-Blog")!=-1)return;j.parentNode.insertBefore(c,j)}}}a()}
function H(){for(var a=document.getElementsByTagName("div"),b=[],c=0;c<a.length;c++)a[c].className==w&&b.push(a[c]);return b}
function D(a){function b(a){function b(a,d){for(var c=a.b.getElementsByTagName("input"),e=0;e<c.length;e++)if(c[e].getAttribute("name")==d)return c[e].getAttribute("value");return null}this.b=a;this.a=this.e=g;this.i=function(){return this.b};this.k=function(){return this.e};this.f=function(){this.e=f};this.j=function(){return this.a};this.c=function(){var a=b(this,x);!a&&typeof wumiiPermaLink!="undefined"&&(a=wumiiPermaLink);return!a?(this.a=f,document.location.href):a};this.d=function(){var a=b(this,
y);!a&&typeof wumiiTitle!="undefined"&&(a=wumiiTitle);return a?a:document.title};this.g=function(){var a=this.c().toLowerCase();return a.indexOf("http://big5.ifeng.com/gate/big5/blog.ifeng.com/")==0||a.indexOf(".iresearch.cn/")!=-1||a.indexOf("http://www.umiwi.com/")==0}}for(var c=[],d=0;d<a.length;d++)c[d]=new b(a[d]);return c}
function E(a,b,c){var d="&num=4&mode=3&v="+encodeURIComponent("")+("&pf="+encodeURIComponent(""))+("&theme="+encodeURIComponent("")),a=(typeof wumiiDebugServer!="undefined"?wumiiDebugServer:"http://app.wumii.com")+"/ext/relatedItems?url="+encodeURIComponent(a)+"&title="+encodeURIComponent(b)+"&fromlocation="+encodeURIComponent(c);typeof wumiiParams!="undefined"?(wumiiParams.indexOf("pf=WordPress")!=-1&&(wumiiParams=wumiiParams.replace(/&#038;/g,"&")),a+=wumiiParams):
a+=d;typeof wumiiSitePrefix!="undefined"&&wumiiSitePrefix&&(a+="&sitePrefix="+encodeURIComponent(wumiiSitePrefix));d=document.createElement("script");d.type="text/javascript";d.src=a;document.getElementsByTagName("head")[0].appendChild(d)}
function F(){for(var a=0;a<v.length;a++){var b=v[a],c;if(b.e)c=g;else{c=window.innerHeight||document.documentElement.clientHeight;for(var d=b.b,e=0;d!=null;)e+=d.offsetTop,d=d.offsetParent;d=e-(window.pageYOffset||document.documentElement.scrollTop||document.body.scrollTop||0);c=d>=-400&&d<=800+c}c&&(b.f(),E(b.c(),b.d(),b.a))}}
function G(){if(window.addEventListener)window.addEventListener("scroll",function(){F()},g),window.addEventListener("resize",function(){F()},g);else if(window.attachEvent)window.attachEvent("onscroll",function(){F()}),window.attachEvent("onresize",function(){F()});else if(document.getElementById)window.onload=function(){for(var a=0;a<v.length;a++)wumiiDiv.f(),E(wumiiDiv.c(),wumiiDiv.d(),wumiiDiv.a)}};})();
