#!/bin/sh

. /lib/dracut-lib.sh

while [ $# -gt 0 ]; do
    case "$1" in
	--onetime)
	    onetime="yes";;
	--settled)
	    queue="-settled";;
	--timeout)
	    queue="-timeout";;
	--unique)
	    unique="yes";;
	--name)
	    name="$2";shift;;
	*)
	    break;;
    esac
    shift
done

if [ -z "$unique" ]; then
	job="${name}$$"
else
	job="${name:-$1}"
	job=${job##*/}
fi


if [ -n "$onetime" ]; then
   { 
       echo '[ -e "$job" ] && rm "$job"'
       echo "$@" 
   } > "/tmp/$$-${job}.sh"
else
   echo "$@" > "/tmp/$$-${job}.sh"
fi

mv -f "/tmp/$$-${job}.sh" "/initqueue${queue}/${job}.sh"
[ -z "$queue" ] && >> /initqueue/work

