var DISQUS=function(b){var h=b.DISQUS||{};h.AssertionError=function(d){this.message=d};h.AssertionError.prototype.toString=function(){return"Assertion Error: "+(this.message||"[no message]")};h.assert=function(d,g,e){if(!d)if(e)b.console&&b.console.log("DISQUS assertion failed: "+g);else throw new h.AssertionError(g);};var d=[];h.define=function(f,g){typeof f==="function"&&(g=f,f="");for(var e=f.split("."),a=e.shift(),c=h,n=(g||function(){return{}}).call({overwrites:function(a){a.__overwrites__=!0;
return a}},b);a;)c=c[a]?c[a]:c[a]={},a=e.shift();for(var l in n)n.hasOwnProperty(l)&&(!n.__overwrites__&&c[l]!==null&&h.assert(!c.hasOwnProperty(l),"Unsafe attempt to redefine existing module: "+l,!0),c[l]=n[l],d.push(function(a,c){return function(){delete a[c]}}(c,l)));return c};h.use=function(d){return h.define(d)};h.cleanup=function(){for(var f=0;f<d.length;f++)d[f]()};return h}(window);
DISQUS.define(function(b,h){var d=b.DISQUS,f=b.document,g=f.getElementsByTagName("head")[0]||f.body,e={running:!1,timer:null,queue:[]};d.defer=function(a,c){function d(){var a=e.queue;if(a.length===0)e.running=!1,clearInterval(e.timer);for(var c=0,g;g=a[c];c++)g[0]()&&(a.splice(c--,1),g[1]())}e.queue.push([a,c]);d();if(!e.running)e.running=!0,e.timer=setInterval(d,100)};d.each=function(a,c){var d=a.length,g=Array.prototype.forEach;if(isNaN(d))for(var e in a)a.hasOwnProperty(e)&&c(a[e],e,a);else if(g)g.call(a,
c);else for(g=0;g<d;g++)c(a[g],g,a)};d.extend=function(a){d.each(Array.prototype.slice.call(arguments,1),function(c){for(var d in c)a[d]=c[d]});return a};d.serializeArgs=function(a){var c=[];d.each(a,function(a,d){a!==h&&c.push(d+(a!==null?"="+encodeURIComponent(a):""))});return c.join("&")};d.isString=function(a){return Object.prototype.toString.call(a)==="[object String]"};d.serialize=function(a,c,g){c&&(a+=~a.indexOf("?")?a.charAt(a.length-1)=="&"?"":"&":"?",a+=d.serializeArgs(c));if(g)return c=
{},c[(new Date).getTime()]=null,d.serialize(a,c);c=a.length;return a.charAt(c-1)=="&"?a.slice(0,c-1):a};d.require=function(a,c,e,b,h){function j(a){if(a.type=="load"||/^(complete|loaded)$/.test(a.target.readyState))b&&b(),q&&clearTimeout(q),d.bean.remove(a.target,p,j)}var k=f.createElement("script"),p=k.addEventListener?"load":"readystatechange",q=null;k.src=d.serialize(a,c,e);k.async=!0;k.charset="UTF-8";(b||h)&&d.bean.add(k,p,j);h&&(q=setTimeout(function(){h()},2E4));g.appendChild(k);return d};
d.requireStylesheet=function(a,c,e){var b=f.createElement("link");b.rel="stylesheet";b.type="text/css";b.href=d.serialize(a,c,e);g.appendChild(b);return d};d.requireSet=function(a,c,g){var e=a.length;d.each(a,function(a){d.require(a,{},c,function(){--e===0&&g()})})};d.injectCss=function(a){var c=f.createElement("style");c.setAttribute("type","text/css");a=a.replace(/\}/g,"}\n");b.location.href.match(/^https/)&&(a=a.replace(/http:\/\//g,"https://"));c.styleSheet?c.styleSheet.cssText=a:c.appendChild(f.createTextNode(a));
g.appendChild(c)};d.isString=function(a){return Object.prototype.toString.call(a)==="[object String]"}});
DISQUS.define("JSON",function(){function b(a){return a<10?"0"+a:a}function h(c){a.lastIndex=0;return a.test(c)?'"'+c.replace(a,function(a){var c=l[a];return typeof c==="string"?c:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+c+'"'}function d(a,e){var b,f,j,k,l=c,m,i=e[a];i&&typeof i==="object"&&typeof i.toJSON==="function"&&!g&&(i=i.toJSON(a));typeof o==="function"&&(i=o.call(e,a,i));switch(typeof i){case "string":return h(i);case "number":return isFinite(i)?String(i):"null";case "boolean":case "null":return String(i);
case "object":if(!i)return"null";c+=n;m=[];if(Object.prototype.toString.apply(i)==="[object Array]"){k=i.length;for(b=0;b<k;b+=1)m[b]=d(b,i)||"null";j=m.length===0?"[]":c?"[\n"+c+m.join(",\n"+c)+"\n"+l+"]":"["+m.join(",")+"]";c=l;return j}if(o&&typeof o==="object"){k=o.length;for(b=0;b<k;b+=1)f=o[b],typeof f==="string"&&(j=d(f,i))&&m.push(h(f)+(c?": ":":")+j)}else for(f in i)Object.hasOwnProperty.call(i,f)&&(j=d(f,i))&&m.push(h(f)+(c?": ":":")+j);j=m.length===0?"{}":c?"{\n"+c+m.join(",\n"+c)+"\n"+
l+"}":"{"+m.join(",")+"}";c=l;return j}}var f={},g=!1;if(typeof Date.prototype.toJSON!=="function")Date.prototype.toJSON=function(){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+b(this.getUTCMonth()+1)+"-"+b(this.getUTCDate())+"T"+b(this.getUTCHours())+":"+b(this.getUTCMinutes())+":"+b(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(){return this.valueOf()};var e=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
a=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,c,n,l={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},o;f.stringify=function(a,g,e){var b;n=c="";if(typeof e==="number")for(b=0;b<e;b+=1)n+=" ";else typeof e==="string"&&(n=e);if((o=g)&&typeof g!=="function"&&(typeof g!=="object"||typeof g.length!=="number"))throw Error("JSON.stringify");return d("",{"":a})};f.parse=function(a,c){function g(a,
d){var e,b,f=a[d];if(f&&typeof f==="object")for(e in f)Object.hasOwnProperty.call(f,e)&&(b=g(f,e),b!==void 0?f[e]=b:delete f[e]);return c.call(a,d,f)}var d,a=String(a);e.lastIndex=0;e.test(a)&&(a=a.replace(e,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return d=eval("("+a+")"),
typeof c==="function"?g({"":d},""):d;throw new SyntaxError("JSON.parse");};var j={a:[1,2,3]},k,p;if(Object.toJSON&&Object.toJSON(j).replace(/\s/g,"")==='{"a":[1,2,3]}')k=Object.toJSON;typeof String.prototype.evalJSON==="function"&&(j='{"a":[1,2,3]}'.evalJSON(),j.a&&j.a.length===3&&j.a[2]===3&&(p=function(a){return a.evalJSON()}));(function(){var a=[1,2,3];typeof a.toJSON==="function"&&(a=a.toJSON(),g=!(a&&a.length===3&&a[2]===3))})();if(g||!k||!p)return{stringify:f.stringify,parse:f.parse};return{stringify:k,
parse:p}});
DISQUS.define("Bus",function(){function b(a){a=a.split("/");return a[0]+"//"+a[2]}var h=DISQUS.use("JSON"),d=window.location.hash.slice(1),f=window.opener||window.parent,g=document.referrer,e={};e.client=b(document.location.href);e.host=g?b(g):e.client;return{origins:e,messageHandler:function(a){var c;try{c=DISQUS.JSON.parse(a.data)}catch(d){return}if(!c.name||!(c.name[0]==="!"&&a.origin!==e.client))switch(c.scope){case "client":DISQUS.Bus.trigger(c.name,c.data)}},postMessage:function(a){a.sender=d;
a=h.stringify(a);f.postMessage(a,"*")},sendHostMessage:function(a,c){c=c||[];DISQUS.Bus.postMessage({scope:"host",name:a,data:c})},sendGlobalMessage:function(a,c){c=c||[];DISQUS.Bus.postMessage({scope:"global",name:a,data:c})}}});_.extend(DISQUS.Bus,Backbone.Events);
$(document).ready(function(){var b=window.addEventListener?window.addEventListener:window.attachEvent,h=window.addEventListener?"message":"onmessage";if(!b)throw Error("No event support.");b(h,DISQUS.Bus.messageHandler,!1);window.onunload=function(){DISQUS.Bus.sendHostMessage("die")}});
DISQUS.define(function(){var b={apiKey:"E8Uh5l5fHZ6gD8U3KycjAIAk46f68Zw7C6eW8WSjZvCLXebZ7p0r1yrYDrLilk2F",debug:!1,browser:{mobile:/iPhone|Android|iPod|iPad|webOS|Mobile Safari|Windows Phone|BlackBerry|Opera Mini|IEMobile/i.test(navigator.userAgent)}};if(typeof require!=="undefined"&&typeof require==="function")b.bean=require("bean");return b});
DISQUS.define("strings",function(){function b(b){var g=d[b];return g!==void 0?g:b}function h(d,g){return d.replace(/%\(\w+\)s/g,function(e){var e=e.slice(2,-2),a="";e in g?a=g[e]!==void 0&&g[e]!==null?g[e].toString():"":DISQUS.logError&&DISQUS.logError("Key `"+e+"` not found in context for: ",d);return a})}var d={};DISQUS.interpolate=h;DISQUS.modules={};window.gettext=b;return{get:b,interpolate:h,translations:d}});
DISQUS.define("time",function(){return{ISO_8601:"YYYY-MM-DDTHH:mm:ssZ",assureTzOffset:function(b){return b.indexOf("+")>=0?b:b+"+00:00"}}});
DISQUS.define("urls",function(){var b=DISQUS.debug?"/js/src/embed/next/vglnk.js":"/build/next/alfie.js",h=encodeURIComponent(document.referrer),d={root:"http://disqus.com",media:"http://mediacdn.disqus.com/1371678751",translations:"http://mediacdn.disqus.com/1371678751/build/lang",loading:"http://mediacdn.disqus.com/1371678751/html/simple-loading.html",realertime:"",juggler:"",login:"https://disqus.com/next/login/",api:"http://disqus.com/api/3.0/",apiSecure:"https://disqus.com/api/3.0/",logout:"http://disqus.com/logout/?redirect="+
h,editProfile:"http://disqus.com/account/",verifyEmail:"https://disqus.com/next/verify/",authorize:"https://disqus.com/api/oauth/2.0/authorize/",moderate:"http://disqus.com/admin/moderate/",oauth:{twitter:"http://disqus.com/_ax/twitter/begin/",google:"http://disqus.com/_ax/google/begin/",facebook:"http://disqus.com/_ax/facebook/begin/"},avatar:{generic:"http://mediacdn.disqus.com/1371678751/images/noavatar92.png"},linkAffiliatorClient:"http://mediacdn.disqus.com/1371678751"+b};window.location.protocol===
"https:"&&(d=_.extend(d,{root:"",media:"",translations:"https://securecdn.disqus.com/1371678751/build/lang",loading:"/html/simple-loading.html",api:d.apiSecure,logout:"https://disqus.com/logout/?redirect="+h,editProfile:"https://disqus.com/account/",moderate:"https://disqus.com/admin/moderate/",oauth:{twitter:"https://disqus.com/_ax/twitter/begin/",google:"https://disqus.com/_ax/google/begin/",facebook:"http://disqus.com/_ax/facebook/begin/"},avatar:{generic:"/images/noavatar92.png"},linkAffiliatorClient:""+
b}));return d});DISQUS.define("templates",function(){function b(d,b){return Handlebars.partials[d](b||{},{data:h})}var h={urls:DISQUS.urls,gettext:DISQUS.strings.get,sso:null};DISQUS.renderBlock=b;DISQUS.templateGlobals=h;return{globals:h,render:b}});
DISQUS.define("api",function(){function b(d){function e(c){var f=c.originalEvent.origin;DISQUS.urls.apiSecure.slice(0,f.length)===f&&(c=DISQUS.JSON.parse(c.originalEvent.data),c.requestId===a&&(f=c.code===0?d.success:d.error,delete c.requestId,(f||function(){})(c),document.body.removeChild(h),document.body.removeChild(b),$(window).off("message",e)))}var a=_.uniqueId("ft_"),c=document.createElement("div"),b=document.createElement("form"),f="frame_"+a,h;c.innerHTML='<iframe name="'+f+'"></iframe>';
h=c.childNodes[0];b.target=f;b.action=d.url.replace(".json",".pm");b.method=d.method||"GET";d.data=_.extend(d.data,{callback:a,referrer:document.referrer});_.each(d.data,function(a,c){a===!0?a=[1]:a===!1?a=[0]:a===null?a=[""]:_.isArray(a)||(a=[a]);_.each(a,function(a){var d=document.createElement("input");d.type="hidden";d.name=c;d.value=a;b.appendChild(d)})});$(window).on("message",e);document.body.appendChild(h);document.body.appendChild(b);b.submit()}function h(b){b=_.defaults(b,d);b.data=b.data||
{};b.data.api_key=DISQUS.apiKey;return $.ajax(b)}var d={},f={defaults:function(b){var e,a,c;for(e in b)a=b[e],c=d[e],_.isObject(a)&&_.isObject(c)?_.extend(c,a):d[e]=a},headers:function(b){b=_.extend({},d.headers,b);d.headers=_.pick(b,_.map(b,function(b,a){if(b)return a}));return d.headers},getURL:function(b,d){d=d||{};if(d.secure||window.location.protocol==="https:")return DISQUS.urls.apiSecure+b;return DISQUS.urls.api+b},ajax:h,call:function(d,e){e=e||{};e.url=DISQUS.api.getURL(d,{secure:e.secure});
e.data=_.extend(e.data||{},{api_key:DISQUS.apiKey});this.trigger("call",e);var a=(e.secure?b:h)(e);a&&a.always(_.bind(this.trigger,this,"complete"));return a}};_.extend(f,Backbone.Events);return f});
(function(b){var h=DISQUS.Bus,d=DISQUS.api.getURL("internal/switches/list.jsonp");b.switches_jsonp_cb=function(b){h.sendHostMessage("switches.received",b.response)};h.on("fetch",function(b){b=b||{};b.data=b.data||{};b.data.callback="switches_jsonp_cb";b.data.api_key=DISQUS.apiKey;b=DISQUS.serialize(d,b.data,!1);DISQUS.require(b)});h.sendHostMessage("ready")})(this);